[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
reqwest = "0.11.13"
tokio = { version = "1.22.0", features = ["rt", "macros"] }
